### ISSUE TITLE
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by wily-1** [plokmijnuhby/CustomHubs#1]

**Comment by wily-1** [comment]
1st: how do i dm you?

2nd: i use windows.

3rd: when i typed the `MonoMod.exe Assembly-CSharp.dll` thing, this `Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'` have showed and it did not have genereted a "MONOMODDED_Assembly-CSharp.dll" file.

so what do i do?

**Comment by plokmijnuhby** [comment]
DM me on discord. Or possibly email me.
