### ISSUE TITLE
.png files

### ISSUE THREAD

**Issue by bruhdot1** [plokmijnuhby/CustomHubs#2]
I don't know how to set up the images on each world, I screenshotted but realized you need no player on the screen, So is there like a bot to setup the images or smth?

**Comment by plokmijnuhby** [comment]
If you attempt to make a hub file with the images not present, the mod should open all the levels without the player and take screenshots for you. Is this feature not working for you?

**Comment by bruhdot1** [comment]
I didnt know that, Thank you so much!
