### ISSUE TITLE
"Error failed to open custom level"

### ISSUE THREAD

**Issue by yeetboi112** [plokmijnuhby/CustomHubs#3]
If I tried to open my custom hub it couldn't load since it had an error, I'll try to show you the hub related files.
![area data](https://user-images.githubusercontent.com/78233984/177645852-f81fde23-d18a-44fc-92ce-caef6ead5382.PNG)
![puzzle data](https://user-images.githubusercontent.com/78233984/177645921-21d78355-5a19-424e-9148-807f9e968af0.PNG)
![puzzle data 2](https://user-images.githubusercontent.com/78233984/177645956-f0b62798-4d4c-4584-9864-576a57df7c0c.PNG)
![puzzle lines](https://user-images.githubusercontent.com/78233984/177646020-e20c0eb7-6b6f-40d8-9cdc-ddc03686cf61.PNG)
![puzzle lines 2](https://user-images.githubusercontent.com/78233984/177646127-c49b20d8-89b7-406c-9138-7f51c3454c6c.PNG)
I think the hub's good; it includes the levels that are in the file and walls (of course). Is there something else I should keep note on?

**Comment by yeetboi112** [comment]
If you need to see the hub also, here
[hub.txt](https://github.com/plokmijnuhby/CustomHubs/files/9063963/hub.txt)
.

**Comment by yeetboi112** [comment]
I have an issue with a specific thing so I'm going to close this issue.

**Comment by plokmijnuhby** [comment]
uh okay
